# TestReport is the single aggregated report for a TestRun, generated by
# ResultAggregator once every Job is terminal (fan-in). success_rate is stored
# as a percentage (0..100). There is exactly one report per TestRun.
class TestReport < ApplicationRecord
  belongs_to :test_run

  validates :total_tests, :passed_tests, :failed_tests, :skipped_tests, :flaky_tests,
            numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :duration_ms,
            numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :success_rate,
            numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }
  validates :generated_at, presence: true
end
